### ISSUE TITLE
Error: The requested accessory 'SmartThingsHelloHome' was not registered by any plugin.

### ISSUE THREAD

**Issue by sebastienb** [arcreative/homebridge-smartthings-routine#2]
HI i get this error when i try to run homebridge. I made sure to install the plugin and also copy the config from the smart app to my config.json. I added the config to the accessories section.

**Comment by arcreative** [comment]
Can you try changing the accessories named "SmartThingsHelloHome" in your `config.json` to "SmartThingsRoutine" and let me know if that works?

**Comment by arcreative** [comment]
Updated the Groovy file to account for this as well--try it out and reopen if still not working :-)
